<a href="https://colab.research.google.com/github/Akisn277/Data-Science-Sheets/blob/main/Data_Science_Sheet_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EMPLOYEE RECORDS- Data cleaning, dealing with NaN, Updating col name

In [2]:
import pandas as pd

In [3]:
emp_rec={
    "Emp_id":[101,102,103,104,105],
    "Name":["Aki","Indhu","Niha","Aathu","Steph"],
    "Designation":["Developer","CEO","Engineer","CFO","Manager"],
    "Salary":[1000000,10,10000,200000,30000],
    "Experience":[3,4,5,6,6],
    "Age":[20,21,22,23,24]
}

df=pd.DataFrame(emp_rec)
print(df)

   Emp_id   Name Designation   Salary  Experience  Age
0     101    Aki   Developer  1000000           3   20
1     102  Indhu         CEO       10           4   21
2     103   Niha    Engineer    10000           5   22
3     104  Aathu         CFO   200000           6   23
4     105  Steph     Manager    30000           6   24

In [5]:
df_new=df[df['Salary'] >= 10000]
print(df_new)

   Emp_id   Name Designation   Salary  Experience  Age
0     101    Aki   Developer  1000000           3   20
2     103   Niha    Engineer    10000           5   22
3     104  Aathu         CFO   200000           6   23
4     105  Steph     Manager    30000           6   24

In [8]:
new_data= {
    "Emp_id":[106],
    "Name":["Cindy"],
    "Salary":[75000],
    "Experience":[2],
    "Age":[28]
}

df_newrow=pd.DataFrame(new_data)
df_updated = pd.concat([df, df_newrow], ignore_index=True)
print(df_updated)

   Emp_id   Name Designation   Salary  Experience  Age
0     101    Aki   Developer  1000000           3   20
1     102  Indhu         CEO       10           4   21
2     103   Niha    Engineer    10000           5   22
3     104  Aathu         CFO   200000           6   23
4     105  Steph     Manager    30000           6   24
5     106  Cindy         NaN    75000           2   28

In [9]:
df_updated['Designation'] = df_updated['Designation'].fillna('Unknown')
display(df_updated)

   Emp_id   Name Designation   Salary  Experience  Age
0     101    Aki   Developer  1000000           3   20
1     102  Indhu         CEO       10           4   21
2     103   Niha    Engineer    10000           5   22
3     104  Aathu         CFO   200000           6   23
4     105  Steph     Manager    30000           6   24
5     106  Cindy     Unknown    75000           2   28

In [11]:
df_updated=df_updated.rename(columns={'Experience':'Exp'})
display(df_updated)

   Emp_id   Name Designation   Salary  exp  Age
0     101    Aki   Developer  1000000    3   20
1     102  Indhu         CEO       10    4   21
2     103   Niha    Engineer    10000    5   22
3     104  Aathu         CFO   200000    6   23
4     105  Steph     Manager    30000    6   24
5     106  Cindy     Unknown    75000    2   28

In [12]:
df_updated['Age']=df_updated['Age'] + 3
display(df_updated)

   Emp_id   Name Designation   Salary  exp  Age
0     101    Aki   Developer  1000000    3   23
1     102  Indhu         CEO       10    4   24
2     103   Niha    Engineer    10000    5   25
3     104  Aathu         CFO   200000    6   26
4     105  Steph     Manager    30000    6   27
5     106  Cindy     Unknown    75000    2   31

STUDENT RECORDS- Merge(inner,outer,left,right),Concat

In [14]:
student_data = {
    'Roll Num': [1, 2, 3, 4, 5],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Subject1_Marks': [85, 78, 92, 65, 88],
    'Subject2_Marks': [70, 82, 89, 75, 95]
}

df_students1 = pd.DataFrame(student_data)
print(df_students1.head())

   Roll Num     Name  Subject1_Marks  Subject2_Marks
0         1    Alice              85              70
1         2      Bob              78              82
2         3  Charlie              92              89
3         4    David              65              75
4         5      Eve              88              95

In [16]:
student_data2 = {
    'Roll Num': [3, 4, 5, 6, 7],
    'Name': ['Charlie', 'David', 'Eve', 'Frank', 'Grace'],
    'Subject3_Marks': [70, 85, 90, 75, 80],
    'Subject4_Marks': [60, 70, 80, 85, 90]
}

df_students2 = pd.DataFrame(student_data2)
print(df_students2.head())

   Roll Num     Name  Subject3_Marks  Subject4_Marks
0         3  Charlie              70              60
1         4    David              85              70
2         5      Eve              90              80
3         6    Frank              75              85
4         7    Grace              80              90

In [18]:
df_inner_merge = pd.merge(df_students1, df_students2, on='Roll Num', how='inner')
print(df_inner_merge)

   Roll Num   Name_x  Subject1_Marks  Subject2_Marks   Name_y  Subject3_Marks  \
0         3  Charlie              92              89  Charlie              70
1         4    David              65              75    David              85
2         5      Eve              88              95      Eve              90

   Subject4_Marks
0              60
1              70
2              80

In [19]:
df_outer_merge = pd.merge(df_students1, df_students2, on='Roll Num', how='outer')
print(df_outer_merge)

   Roll Num   Name_x  Subject1_Marks  Subject2_Marks   Name_y  Subject3_Marks  \
0         1    Alice            85.0            70.0      NaN             NaN
1         2      Bob            78.0            82.0      NaN             NaN
2         3  Charlie            92.0            89.0  Charlie            70.0
3         4    David            65.0            75.0    David            85.0
4         5      Eve            88.0            95.0      Eve            90.0
5         6      NaN             NaN             NaN    Frank            75.0
6         7      NaN             NaN             NaN    Grace            80.0

   Subject4_Marks
0             NaN
1             NaN
2            60.0
3            70.0
4            80.0
5            85.0
6            90.0

In [22]:
df_right_merge = pd.merge(df_students1, df_students2, on='Roll Num', how='right')
print(df_right_merge)

   Roll Num   Name_x  Subject1_Marks  Subject2_Marks   Name_y  Subject3_Marks  \
0         3  Charlie            92.0            89.0  Charlie              70
1         4    David            65.0            75.0    David              85
2         5      Eve            88.0            95.0      Eve              90
3         6      NaN             NaN             NaN    Frank              75
4         7      NaN             NaN             NaN    Grace              80

   Subject4_Marks
0              60
1              70
2              80
3              85
4              90

SALES RECORDS- Pivoting and melting

In [25]:
data = {
    'Region': ['East', 'West', 'East', 'West', 'East', 'West'],
    'Product': ['A', 'A', 'B', 'B', 'A', 'B'],
    'Month': ['Jan', 'Jan', 'Jan', 'Jan', 'Feb', 'Feb'],
    'Sales': [100, 150, 200, 120, 110, 180]
}
df_sales = pd.DataFrame(data)
display(df_sales)

  Region Product Month  Sales
0   East       A   Jan    100
1   West       A   Jan    150
2   East       B   Jan    200
3   West       B   Jan    120
4   East       A   Feb    110
5   West       B   Feb    180

### Pivot Operation

The `pivot` function is used to reshape data (produce a 'pivot' table) based on column values. It takes three main arguments:
- `index`: Column to use to make new frame's index.
- `columns`: Column to use to make new frame's columns.
- `values`: Column(s) to use for populating new frame's values.

Let's pivot our `df_sales` to see `Sales` for each `Region` across different `Product` types.

In [29]:
df_pivot = df_sales.pivot_table(index=['Month', 'Region'], columns='Product', values='Sales', aggfunc='sum')
display(df_pivot)

Product           A      B
Month Region
Feb   East    110.0    NaN
      West      NaN  180.0
Jan   East    100.0  200.0
      West    150.0  120.0

### Melt Operation

The `melt` function is the inverse of `pivot`. It transforms or 'unpivots' DataFrames from a wide format to a long format. It's useful when you want to convert columns into rows.
- `id_vars`: Columns to use as identifier variables.
- `value_vars`: Columns to unpivot. If not specified, all columns not set as `id_vars` will be unpivoted.
- `var_name`: Name for the new 'variable' column.
- `value_name`: Name for the new 'value' column.

Let's melt our original `df_sales` DataFrame, treating `Region`, `Product`, and `Month` as identifier variables and `Sales` as the value variable. This might seem redundant for `df_sales` as it's already in a long format, but it's a good way to understand the concept. A more common use case for melt would be to unpivot the `df_pivot` DataFrame.

In [27]:
df_melted_original = df_sales.melt(id_vars=['Region', 'Product', 'Month'], value_vars=['Sales'], var_name='Metric', value_name='Amount')
display(df_melted_original)

  Region Product Month Metric  Amount
0   East       A   Jan  Sales     100
1   West       A   Jan  Sales     150
2   East       B   Jan  Sales     200
3   West       B   Jan  Sales     120
4   East       A   Feb  Sales     110
5   West       B   Feb  Sales     180

In [30]:
df_melted_from_pivot = df_pivot.reset_index().melt(id_vars=['Month', 'Region'], var_name='Product', value_name='Sales')
display(df_melted_from_pivot)

  Month Region Product  Sales
0   Feb   East       A  110.0
1   Feb   West       A    NaN
2   Jan   East       A  100.0
3   Jan   West       A  150.0
4   Feb   East       B    NaN
5   Feb   West       B  180.0
6   Jan   East       B  200.0
7   Jan   West       B  120.0